# fly.toml app configuration file generated for firewatch-c on 2025-06-20T20:13:55+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'firewatch-c'
primary_region = 'syd'

[env]
  CAMPFIRE = 'unusualdatabase'
  CF_PORT = '5000'
  CF_UDP_PORT = '5001'


[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# For the tcp service
[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
  port = 5000

# For the udp service
[[services]]
  internal_port = 5001
  protocol = "udp"

  [[services.ports]]
  port = 5001